### ISSUE TITLE
problems with plugin usage in GitHub Actions

### ISSUE THREAD

**Issue by svntmr** [atollk/flake8-import-restrictions#17]
Hi @atollk 👋 

I'm trying to execute `flake8` with your plugin from GitHub actions

Here is content of my `.flake8`:

```ini
[flake8]
# black compatibility
max-line-length = 88
extend-ignore = E203
extend-exclude =
    .mypy_cache,
    .pytest_cache,
    venv,
    htmlcov,
    .coverage,
    .coverage.xml,
    __pycache__
imr241_exclude =
    typing,
    __future__
```

My requirements file:

```
flake8==5.0.4
flake8-import-restrictions==2.0.1
```

I can execute `flake8 . --config .flake8` locally (using python 3.11.6 on MacOS 14.1.1) - it runs fine  

Though it fails in GitHub actions (I'm using python 3.11.6 on ubuntu-latest there) and hangs up the job

Example error message from GitHub Actions:

```
Run flake8 . --config .flake8
  flake8 . --config .flake8
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.6/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.6/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.6/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.6/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.6/x64/lib
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: No constructor defined
```

This problem also occurs if flake8 is executed from `pre-commit`, here is an example pre-commit hook that also hangs up the process:

```yaml
default_language_version:
  python: python3.11

repos:
  - repo: local
    hooks:
      - id: flake8
        name: run flake8
        language: system
        entry: flake8 <folder with my code> --config <path to .flake8>
        pass_filenames: false
        always_run: true
        types: [python]
```

please, let me know if you need more info

**Comment by atollk** [comment]
Thanks for the report. I don't really see anything specific to flake8-import-restrictions in the stack trace. Did you check that the error doesn't also occur with the same configuration, just without my plugin?

**Comment by svntmr** [comment]
follow up: I tried to reproduce this problem locally in a smaller repo - no success
gonna give it another try tomorrow on a bigger codebase

**Comment by svntmr** [comment]
I’m not able to reproduce this problem anymore, closing this issue
